### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by AStoker** [FederationOfFathers/dashboard-ui#1]
Move these notes into a readable feature list to implement and create issues for each:

> so I am off in destiny land putting together enough of an API Client to pull the destiny stats we need _right now_ into a database  
> I won’t dick with the dashboard until I get back from there  
> so as a reminder the user-facing MVP here to tell people about the new tool is:  
> the private groups feature  
> damnbot can be invited to private groups  
> admins can mark those as visible  
> then anyone can browse the visible groups and join them from the ui  
> my thought is that admins see the same ui except all groups are included not just visible ones for them and they get the ability to toggle visibility  
> all that is doable with the api right now (edited)  
> now each member should have their own page. it’s gonna be super empty for now. but on login they should default to their page from /  
> so like… /m/bobthelob  or maybe /@/ or something?  
> that sets the stage that there’s s a thing being built up here _and_ that the groups thing isn’t “the app"  
> it’s a part of it

**Comment by apokalyptik** [comment]
Added issues:
- #2 
- #3 
- #4
